#!/bin/bash

set -x

if [ -z "$PUBLIC_IP" ]; then
    ip -o -4 a
    PUBLIC_IP=$(ip -o -4 a | awk '$2 == "eth0" { gsub(/\/.*/, "", $4); print $4 }')
fi

sed -i -e "s/interface=.*/interface=$PUBLIC_IP/" /etc/rtpengine/rtpengine.conf

exec rtpengine --config-file /etc/rtpengine/rtpengine.conf

# init ends here
