#!/bin/bash

mkdir -p /etc/ansible

cat > /etc/ansible/hosts <<EOF
[all]
localhost ansible_connection=local ansible_python_interpreter="{{ansible_playbook_python}}" rtpengine_interface=eth0 rtpengine_private_address=localhost rtpengine_public_address=localhost
EOF
