---
- name: Delete vanished bullseye-backports repository
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian bullseye-backports main
    state: absent
    update_cache: false

- name: Delete vanished bullseye-backports source repository
  ansible.builtin.apt_repository:
    repo: deb-src http://deb.debian.org/debian bullseye-backports main
    state: absent
    update_cache: false

- name: Upgrade Debian before anything
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  when:
    - debian_upgrade_first
    - debian_upgrade_first_done is undefined
  register: debian_upgrade_first_done
