#!/bin/bash

set +x

/var/lib/dpkg/info/xivo-certs.postinst configure

DATA_DIR="/var/lib/consul"
MASTER_TOKEN_FILE="${DATA_DIR}/master_token"
CONFIG_DIR="/etc/consul.d"
DEFAULT_CONFIG="${CONFIG_DIR}/wazo-config.json"
RUN_DIR="/run/consul"
PID_FILE="${RUN_DIR}/consul.pid"
USER=consul
GROUP=${USER}

# Create the master token file
if [ ! -r ${MASTER_TOKEN_FILE} ]; then
    touch ${MASTER_TOKEN_FILE}
    chown ${USER}:${GROUP} ${MASTER_TOKEN_FILE}
    chmod 600 ${MASTER_TOKEN_FILE}
    token=$(od -An -tx4 -N32 -w /dev/urandom | tr -d " ")
    echo ${token} > ${MASTER_TOKEN_FILE}
fi

# Create the config file
if [ ! -r ${DEFAULT_CONFIG} ]; then
    token=$(cat ${MASTER_TOKEN_FILE})
    cat > ${DEFAULT_CONFIG} <<EOF
{
    "acl_default_policy": "allow",
    "acl_master_token": "${token}",
    "acl_datacenter": "$(hostname -s)",
    "datacenter": "$(hostname -s)",
    "acl_enforce_version_8": false,
    "server": true,
    "bind_addr": "0.0.0.0",
    "client_addr": "0.0.0.0",
    "bootstrap_expect": 1,
    "rejoin_after_leave": true,
    "data_dir": "${DATA_DIR}",
    "pid_file": "${PID_FILE}",
    "disable_update_check": true,
    "log_level": "err",
    "ports": {
        "dns": -1,
        "http": 8500,
        "https": 8501
    },
    "cert_file": "/usr/share/xivo-certs/server.crt",
    "key_file": "/usr/share/xivo-certs/server.key"
}
EOF
    chown ${USER}:${GROUP} ${DEFAULT_CONFIG}
    chmod 600 ${DEFAULT_CONFIG}
fi

mkdir -p ${RUN_DIR}
chown ${USER}:${GROUP} ${RUN_DIR}

exec consul agent -server -data-dir=${DATA_DIR} -config-dir=${CONFIG_DIR} -ui

# init ends here
