- import_tasks: kamailio.yml
  tags:
  - kamailio

- import_tasks: wazo-db.yml
  tags:
  - wazo-db

- import_tasks: wazo-packages.yml
  tags:
  - wazo-packages

- name: Create/Configure SSL certs
  include_role:
    name: wazo-certs

- name: Install Wazo auth
  include_role:
    name: wazo-auth

- name : Wait for wazo-auth is available
  wait_for:
    port: 9497
    delay: 10

- name: Create wazo-auth setup sentinel directory
  file:
    state: directory
    path: /var/lib/ansible/{{ role_name }}

- name: Create a tenant
  shell: >
    wazo-auth-cli tenant create main &&
    touch /var/lib/ansible/{{ role_name }}/tenant_created
  args:
    creates: /var/lib/ansible/{{ role_name }}/tenant_created

- name: Create API client
  shell: >
    wazo-auth-cli user create {{ api_client_name }} --tenant main --password {{ api_client_password }} --purpose external_api &&
    touch /var/lib/ansible/{{ role_name }}/user_created
  args:
    creates: /var/lib/ansible/{{ role_name }}/user_created

- name: Create policy
  shell: >
    wazo-auth-cli policy create api-client-policy --tenant main --acl 'auth.#' &&
    touch /var/lib/ansible/{{ role_name }}/policy_created
  args:
    creates: /var/lib/ansible/{{ role_name }}/policy_created

- name: Enable policy for API client
  shell: >
    wazo-auth-cli user add {{ api_client_name }} --policy api-client-policy &&
    touch /var/lib/ansible/{{ role_name }}/client_policy_associated
  args:
    creates: /var/lib/ansible/{{ role_name }}/client_policy_associated
