#!/bin/bash

# while the TODO are not implemented
if false; then
if [ ! -r /etc/wazo-auth.cfg ]; then
    # TODO get wazo-auth config from Consul
    # TODO transform /etc/wazo-auth.cfg.j2 into /etc/wazo-auth.cfg
    echo PURGE | debconf-communicate wazo-auth
    debconf-set-selections /etc/wazo-auth.cfg
    dpkg-reconfigure wazo-auth --frontend noninteractive

    wazo-auth-keys service update
fi

if [ ! -r /etc/xivo-manage-db.cfg ]; then
    # TODO get xivo-manage-db config from Consul
    # TODO transform /etc/xivo-manage-db.cfg.j2 into /etc/xivo-manage-db.cfg
    echo PURGE | debconf-communicate xivo-manage-db
    debconf-set-selections /etc/xivo-manage-db.cfg
    dpkg-reconfigure xivo-manage-db --frontend noninteractive
    twistd --help-reactors
fi

install -d -o wazo-auth -g wazo-auth /var/run/wazo-auth

exec /usr/bin/wazo-auth
else
    exec bash
fi

# init ends here
