#!/bin/bash

if [ -n "$CONSUL_HTTP_ADDR" ]; then
    exec wazo-router-confd --host 0.0.0.0 --port 8000 --consul-uri $CONSUL_HTTP_ADDR
else
    # only for the build process
    sleep 120
fi

# init ends here
