#SPDX-License-Identifier: MIT-0
---
# tasks file for hackathon

- name: Create wazo-gitd etc directory
  ansible.builtin.file:
    path: "{{ hackathon_gitd_folder }}"
    state: directory
    owner: root
    group: root
    mode: '0755'


- name: Git init "{{ hackathon_gitd_folder }}"
  ansible.builtin.command: git init
  args:
    chdir: "{{ hackathon_gitd_folder }}"

- name: Make etckeeper not complaining when it is invoked by cron
  community.general.git_config:
    name: user.email
    repo: "{{ hackathon_gitd_folder }}"
    scope: local
    value: 'wazo-gitd@localhost'

- name: Make etckeeper not complaining when it is invoked by cron
  community.general.git_config:
    name: user.name
    repo: "{{ hackathon_gitd_folder }}"
    scope: local
    value: 'wazo-gitd@localhost'

- name: Copy each folder into "{{ hackathon_gitd_folder }}"
  ansible.builtin.copy:
    src: "/etc/{{ item }}"
    dest: "{{ hackathon_gitd_folder }}/"
    remote_src: true
    mode: preserve
  loop: "{{ wazo_services }}"

- name: Remove
  ansible.builtin.file:
    path: "/etc/{{ item }}"
    state: absent
  loop: "{{ wazo_services }}"

- name: Create symlinks
  ansible.builtin.file:
    dest: "/etc/{{ item }}"
    src: "{{ hackathon_gitd_folder }}/{{ item }}"
    owner: root
    group: root
    state: link
  loop: "{{ wazo_services }}"

- name: Check git logs
  ansible.builtin.command: git log
  register: _git_log
  ignore_errors: true
  args:
    chdir: "{{ hackathon_gitd_folder }}"

- name: First commit
  ansible.builtin.shell: |
    git add .
    git commit -m "First commit"
  args:
    chdir: "{{ hackathon_gitd_folder }}"
  when: _git_log.rc > 0

- name: Deploy cron
  ansible.builtin.import_tasks: cron.yml

- name: Upload sysconfd config
  ansible.builtin.copy:
    dest: /etc/wazo-sysconfd/conf.d/10-gitd.yml
    content: |
      config_diff:
        repo_path: /etc/wazo-gitd
    owner: root
    group: root
    mode: '0644'
  notify: Restart wazo-sysconfd
